name: maven-jib-build
run-name: Building the Echoserver application
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "${{ github.actor }}"
      - uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: |
          mvn --batch-mode --update-snapshots compile jib:build