name: maven-jib-build
run-name: Building the Echoserver application
on: [push]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: |
          mvn compile jib:build