name: maven-jib-build
run-name: Building the Echoserver application
on: [push]

env:
  USERNAME: ${{ secrets.DOCKER_USERNAME }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: |
          mkdir .docker
          echo “{“auths”:{”https://index.docker.io/v1/":{“username”:"$USERNAME",“password”:"$PASSWORD"}}}" > .docker/config.json
          mvn --batch-mode --update-snapshots compile jib:build